services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - my-network
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: jobs
    networks:
      - my-network
    volumes:
      - jobs_data:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge

volumes:
  jobs_data:
